// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using task_4_library_manger.Repository;

#nullable disable

namespace task_4_library_manger.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20251029141653_DataSeeding")]
    partial class DataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("task_4_library_manger.Entities.Models.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ee4dc1a-3b94-44a6-bd1b-ff23fc4d70d0"),
                            DateOfBirth = new DateTime(1828, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Лев Толстой"
                        },
                        new
                        {
                            Id = new Guid("3bb4602c-3a72-45d3-9786-78bfca23d984"),
                            DateOfBirth = new DateTime(1821, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Фёдор Достоевский"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            DateOfBirth = new DateTime(1860, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Антон Чехов"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8901-bcde-f23456789012"),
                            DateOfBirth = new DateTime(1809, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Николай Гоголь"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-9012-cdef-345678901234"),
                            DateOfBirth = new DateTime(1799, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Александр Пушкин"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-0123-def0-456789012345"),
                            DateOfBirth = new DateTime(1814, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Михаил Лермонтов"
                        });
                });

            modelBuilder.Entity("task_4_library_manger.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("PublishedYear")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7afe6552-9e5c-478d-84be-aeef79965f32"),
                            AuthorId = new Guid("8ee4dc1a-3b94-44a6-bd1b-ff23fc4d70d0"),
                            PublishedYear = new DateOnly(1869, 1, 1),
                            Title = "Война и мир"
                        },
                        new
                        {
                            Id = new Guid("1a2b3c4d-5e6f-7890-abcd-ef1234567890"),
                            AuthorId = new Guid("8ee4dc1a-3b94-44a6-bd1b-ff23fc4d70d0"),
                            PublishedYear = new DateOnly(1857, 1, 1),
                            Title = "Юность"
                        },
                        new
                        {
                            Id = new Guid("2b3c4d5e-6f7a-8901-bcde-f23456789012"),
                            AuthorId = new Guid("8ee4dc1a-3b94-44a6-bd1b-ff23fc4d70d0"),
                            PublishedYear = new DateOnly(1877, 1, 1),
                            Title = "Анна Каренина"
                        },
                        new
                        {
                            Id = new Guid("3c4d5e6f-7a8b-9012-cdef-345678901234"),
                            AuthorId = new Guid("8ee4dc1a-3b94-44a6-bd1b-ff23fc4d70d0"),
                            PublishedYear = new DateOnly(1899, 1, 1),
                            Title = "Воскресение"
                        },
                        new
                        {
                            Id = new Guid("76d98093-1e0d-40f1-9e25-9d6066f0c283"),
                            AuthorId = new Guid("3bb4602c-3a72-45d3-9786-78bfca23d984"),
                            PublishedYear = new DateOnly(1866, 1, 1),
                            Title = "Преступление и наказание"
                        },
                        new
                        {
                            Id = new Guid("4d5e6f7a-8b9c-0123-def0-456789012345"),
                            AuthorId = new Guid("3bb4602c-3a72-45d3-9786-78bfca23d984"),
                            PublishedYear = new DateOnly(1869, 1, 1),
                            Title = "Идиот"
                        },
                        new
                        {
                            Id = new Guid("5e6f7a8b-9c0d-1234-ef01-567890123456"),
                            AuthorId = new Guid("3bb4602c-3a72-45d3-9786-78bfca23d984"),
                            PublishedYear = new DateOnly(1880, 1, 1),
                            Title = "Братья Карамазовы"
                        },
                        new
                        {
                            Id = new Guid("6f7a8b9c-0d1e-2345-f012-678901234567"),
                            AuthorId = new Guid("3bb4602c-3a72-45d3-9786-78bfca23d984"),
                            PublishedYear = new DateOnly(1872, 1, 1),
                            Title = "Бесы"
                        },
                        new
                        {
                            Id = new Guid("7a8b9c0d-1e2f-3456-0123-789012345678"),
                            AuthorId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            PublishedYear = new DateOnly(1904, 1, 1),
                            Title = "Вишнёвый сад"
                        },
                        new
                        {
                            Id = new Guid("8b9c0d1e-2f3a-4567-1234-890123456789"),
                            AuthorId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            PublishedYear = new DateOnly(1901, 1, 1),
                            Title = "Три сестры"
                        },
                        new
                        {
                            Id = new Guid("9c0d1e2f-3a4b-5678-2345-901234567890"),
                            AuthorId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            PublishedYear = new DateOnly(1896, 1, 1),
                            Title = "Чайка"
                        },
                        new
                        {
                            Id = new Guid("0d1e2f3a-4b5c-6789-3456-012345678901"),
                            AuthorId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            PublishedYear = new DateOnly(1899, 1, 1),
                            Title = "Дама с собачкой"
                        },
                        new
                        {
                            Id = new Guid("1e2f3a4b-5c6d-7890-4567-123456789012"),
                            AuthorId = new Guid("b2c3d4e5-f6a7-8901-bcde-f23456789012"),
                            PublishedYear = new DateOnly(1842, 1, 1),
                            Title = "Мёртвые души"
                        },
                        new
                        {
                            Id = new Guid("2f3a4b5c-6d7e-8901-5678-234567890123"),
                            AuthorId = new Guid("b2c3d4e5-f6a7-8901-bcde-f23456789012"),
                            PublishedYear = new DateOnly(1836, 1, 1),
                            Title = "Ревизор"
                        },
                        new
                        {
                            Id = new Guid("3a4b5c6d-7e8f-9012-6789-345678901234"),
                            AuthorId = new Guid("b2c3d4e5-f6a7-8901-bcde-f23456789012"),
                            PublishedYear = new DateOnly(1831, 1, 1),
                            Title = "Вечера на хуторе близ Диканьки"
                        },
                        new
                        {
                            Id = new Guid("4b5c6d7e-8f9a-0123-7890-456789012345"),
                            AuthorId = new Guid("b2c3d4e5-f6a7-8901-bcde-f23456789012"),
                            PublishedYear = new DateOnly(1835, 1, 1),
                            Title = "Тарас Бульба"
                        },
                        new
                        {
                            Id = new Guid("5c6d7e8f-9a0b-1234-8901-567890123456"),
                            AuthorId = new Guid("c3d4e5f6-a7b8-9012-cdef-345678901234"),
                            PublishedYear = new DateOnly(1833, 1, 1),
                            Title = "Евгений Онегин"
                        },
                        new
                        {
                            Id = new Guid("6d7e8f9a-0b1c-2345-9012-678901234567"),
                            AuthorId = new Guid("c3d4e5f6-a7b8-9012-cdef-345678901234"),
                            PublishedYear = new DateOnly(1836, 1, 1),
                            Title = "Капитанская дочка"
                        },
                        new
                        {
                            Id = new Guid("7e8f9a0b-1c2d-3456-0123-789012345678"),
                            AuthorId = new Guid("c3d4e5f6-a7b8-9012-cdef-345678901234"),
                            PublishedYear = new DateOnly(1834, 1, 1),
                            Title = "Пиковая дама"
                        },
                        new
                        {
                            Id = new Guid("8f9a0b1c-2d3e-4567-1234-890123456789"),
                            AuthorId = new Guid("c3d4e5f6-a7b8-9012-cdef-345678901234"),
                            PublishedYear = new DateOnly(1820, 1, 1),
                            Title = "Руслан и Людмила"
                        },
                        new
                        {
                            Id = new Guid("9a0b1c2d-3e4f-5678-2345-901234567890"),
                            AuthorId = new Guid("d4e5f6a7-b8c9-0123-def0-456789012345"),
                            PublishedYear = new DateOnly(1840, 1, 1),
                            Title = "Герой нашего времени"
                        },
                        new
                        {
                            Id = new Guid("0b1c2d3e-4f5a-6789-3456-012345678901"),
                            AuthorId = new Guid("d4e5f6a7-b8c9-0123-def0-456789012345"),
                            PublishedYear = new DateOnly(1840, 1, 1),
                            Title = "Мцыри"
                        },
                        new
                        {
                            Id = new Guid("1c2d3e4f-5a6b-7890-4567-123456789012"),
                            AuthorId = new Guid("d4e5f6a7-b8c9-0123-def0-456789012345"),
                            PublishedYear = new DateOnly(1842, 1, 1),
                            Title = "Демон"
                        },
                        new
                        {
                            Id = new Guid("2d3e4f5a-6b7c-8901-5678-234567890123"),
                            AuthorId = new Guid("d4e5f6a7-b8c9-0123-def0-456789012345"),
                            PublishedYear = new DateOnly(1837, 1, 1),
                            Title = "Бородино"
                        });
                });

            modelBuilder.Entity("task_4_library_manger.Models.Book", b =>
                {
                    b.HasOne("task_4_library_manger.Entities.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("task_4_library_manger.Entities.Models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
